version: "3.9"
services:
  api:
    container_name: flask-container
    build: .
#    entrypoint: python __main__.py
    ports:
      - '4000:4000'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    container_name: redis-container-commander

